### ISSUE TITLE
Chown error in log for /dev/ttyUSB*

### ISSUE THREAD

**Issue by dwightstanley** [stuckless/sagetv-dockers#11]
This error is shown in the logo of a new clean install:
chown: cannot access '/dev/ttyUSB*': No such file or directory
failed to change ownership of '/dev/ttyUSB*' to root:sagetv
chmod: cannot access '/dev/ttyUSB*': No such file or directory
failed to change mode of '/dev/ttyUSB*' from 0000 (---------) to 0000 (---------)

**Comment by CraziFuzzy** [comment]
So, two real options - either check if they exist first, before calling chown, or suppress the error via grep like is done on the folders.  I'm thinking the check prior makes more sense in his instance - can you check for the existence of a wildcarded path though?

**Comment by CraziFuzzy** [comment]
Apparently, like all things linux and bash - the answer is 'sort of': 

http://stackoverflow.com/questions/6363441/check-if-a-file-exists-with-wildcard-in-shell-script
(The edit of the top answer is probably the smoothest way)

**Comment by CraziFuzzy** [comment]
Something like (I haven't tested this):

```
for f in /dev/ttyUSB*; do
	if [ -e "$f" ] ; then
		chown -Rv root:sagetv /dev/ttyUSB* | grep -v 'retained'
		chmod -v 775 /dev/ttyUSB* | grep -v 'retained'
	fi
	break
done

```

if this works, we might be able to expand this method to deal with the lirc* devices.

**Comment by stuckless** [comment]
Fixed

**Comment by dwightstanley** [comment]
Still shows on my system log after updating!?:

chown: cannot access '/dev/ttyUSB*': No such file or directory
failed to change ownership of '/dev/ttyUSB*' to root:sagetv
chmod: cannot access '/dev/ttyUSB*': No such file or directory
failed to change mode of '/dev/ttyUSB*' from 0000 (---------) to 0000 (---------)

Does not appear to cause any problems for me though ...
[SageTV-Docker.txt](https://github.com/stuckless/sagetv-dockers/files/888413/SageTV-Docker.txt)

**Comment by stuckless** [comment]
There is another update to the container (as of this morning).  It appears your are running the update from mar 31, not today.

**Comment by dwightstanley** [comment]
Damn Sean - you are right again - thank you so much for your work!
